# Generated by Django 5.1.5 on 2025-06-13 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pg_grupos_gerenciais',
            },
        ),
        # migrations.CreateModel(
        #     name='PlanilhaGerencial',
        #     fields=[
        #         ('cod_folha', models.CharField(db_column='Cod_folha', max_length=10, primary_key=True, serialize=False)),
        #         ('cod_geral', models.CharField(blank=True, db_column='Cod_Geral', max_length=10, null=True)),
        #         ('razao_social', models.CharField(blank=True, db_column='Razao_Social', max_length=255, null=True)),
        #         ('grupo_economico', models.CharField(blank=True, db_column='Grupo_Economico', max_length=255, null=True)),
        #         ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=50, null=True)),
        #         ('cnpj_original', models.CharField(blank=True, db_column='CNPJ_Original', max_length=50, null=True)),
        #         ('status_do_cliente', models.CharField(blank=True, db_column='Status_do_Cliente', max_length=100, null=True)),
        #         ('inicio_contrato', models.DateField(blank=True, db_column='Inicio_Contrato', null=True)),
        #         ('termino_contrato', models.DateField(blank=True, db_column='Termino_Contrato', null=True)),
        #         ('motivo_termino', models.CharField(blank=True, db_column='Motivo_Termino', max_length=255, null=True)),
        #         ('tributacao', models.CharField(blank=True, db_column='Tributacao', max_length=100, null=True)),
        #         ('sistema', models.CharField(blank=True, db_column='Sistema', max_length=100, null=True)),
        #         ('resp_dp', models.CharField(blank=True, db_column='Resp_DP', max_length=100, null=True)),
        #         ('ramal', models.CharField(blank=True, db_column='Ramal', max_length=50, null=True)),
        #         ('voip', models.CharField(blank=True, db_column='Voip', max_length=50, null=True)),
        #         ('grupo', models.CharField(blank=True, db_column='Grupo', max_length=100, null=True)),
        #         ('data_pagto_salario', models.CharField(blank=True, db_column='Data_Pagto_Salario', max_length=20, null=True)),
        #         ('classificacao', models.CharField(blank=True, db_column='Classificacao', max_length=100, null=True)),
        #         ('sci_report', models.CharField(blank=True, db_column='SCI_Report', max_length=255, null=True)),
        #         ('visitacao', models.CharField(blank=True, db_column='Visitacao', max_length=100, null=True)),
        #         ('matriz', models.CharField(blank=True, db_column='Matriz', max_length=100, null=True)),
        #         ('tempo_demandado', models.CharField(blank=True, db_column='Tempo_Demandado', max_length=100, null=True)),
        #         ('enviadctf', models.CharField(blank=True, db_column='EnviaDCTF', max_length=100, null=True)),
        #         ('classificacao2', models.CharField(blank=True, db_column='Classificacao2', max_length=100, null=True)),
        #         ('cod_folha_520', models.CharField(blank=True, db_column='cod_folha_520', max_length=100, null=True)),
        #     ],
        #     options={
        #         'db_table': 'geral_planilha_gerencial',
        #         'managed': True,
        #     },
        # ),
        migrations.RunSQL('SELECT 1', reverse_sql='SELECT 1'),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('prazo_dias', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'pg_servicos',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('voip', models.CharField(blank=True, max_length=20, null=True)),
                ('ramal', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], max_length=10)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='core.grupogerencial')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pg_responsaveis',
            },
        ),
        migrations.AddField(
            model_name='grupogerencial',
            name='coordenadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_que_coordena', to='core.responsavel'),
        ),
        migrations.CreateModel(
            name='ServicoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('empresa', models.IntegerField()),
                ('competencia', models.CharField(max_length=6)),
                ('identificacao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_servico', models.TextField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_para_resposta', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
            options={
                'db_table': 'pg_servicos_solicitados',
            },
        ),
    ]
