# Generated by Django 5.1.5 on 2025-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('SELECT 1', reverse_sql='SELECT 1'),
        migrations.AlterField(
            model_name='responsavel',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
