# Generated by Django 5.1.5 on 2025-06-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planilhagerencial_alter_responsavel_usuario'),
    ]

    operations = [
        migrations.RunSQL('SELECT 1', reverse_sql='SELECT 1'),
        migrations.AddField(
            model_name='servico',
            name='tempo_execucao',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
