# Generated by Django 5.1.5 on 2025-06-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planilhagerencial_servico_tempo_execucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True)),
                ('dia', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('responsabilidade', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pg_agenda_base',
            },
        ),
        migrations.RunSQL('SELECT 1', reverse_sql='SELECT 1'),
    ]
