# Generated by Django 5.2.5 on 2025-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agendabase_planilhagerencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaGerencial',
            fields=[
                ('cod_folha', models.CharField(db_column='Cod_folha', max_length=10, primary_key=True, serialize=False)),
                ('cod_geral', models.CharField(blank=True, db_column='Cod_Geral', max_length=10, null=True)),
                ('razao_social', models.CharField(blank=True, db_column='Razao_Social', max_length=255, null=True)),
                ('grupo_economico', models.CharField(blank=True, db_column='Grupo_Economico', max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=50, null=True)),
                ('cnpj_original', models.CharField(blank=True, db_column='CNPJ_Original', max_length=50, null=True)),
                ('status_do_cliente', models.CharField(blank=True, db_column='Status_do_Cliente', max_length=100, null=True)),
                ('inicio_contrato', models.DateField(blank=True, db_column='Inicio_Contrato', null=True)),
                ('termino_contrato', models.DateField(blank=True, db_column='Termino_Contrato', null=True)),
                ('motivo_termino', models.CharField(blank=True, db_column='Motivo_Termino', max_length=255, null=True)),
                ('tributacao', models.CharField(blank=True, db_column='Tributacao', max_length=100, null=True)),
                ('sistema', models.CharField(blank=True, db_column='Sistema', max_length=100, null=True)),
                ('resp_dp', models.CharField(blank=True, db_column='Resp_DP', max_length=100, null=True)),
                ('ramal', models.CharField(blank=True, db_column='Ramal', max_length=50, null=True)),
                ('voip', models.CharField(blank=True, db_column='Voip', max_length=50, null=True)),
                ('grupo', models.CharField(blank=True, db_column='Grupo', max_length=100, null=True)),
                ('data_pagto_salario', models.CharField(blank=True, db_column='Data_Pagto_Salario', max_length=20, null=True)),
                ('classificacao', models.CharField(blank=True, db_column='Classificacao', max_length=100, null=True)),
                ('sci_report', models.CharField(blank=True, db_column='SCI_Report', max_length=255, null=True)),
                ('visitacao', models.CharField(blank=True, db_column='Visitacao', max_length=100, null=True)),
                ('matriz', models.CharField(blank=True, db_column='Matriz', max_length=100, null=True)),
                ('tempo_demandado', models.CharField(blank=True, db_column='Tempo_Demandado', max_length=100, null=True)),
                ('enviadctf', models.CharField(blank=True, db_column='EnviaDCTF', max_length=100, null=True)),
                ('classificacao2', models.CharField(blank=True, db_column='Classificacao2', max_length=100, null=True)),
                ('cod_folha_520', models.CharField(blank=True, db_column='cod_folha_520', max_length=100, null=True)),
                ('serv_prest', models.CharField(blank=True, db_column='SERV_PREST', max_length=255, null=True)),
                ('deson', models.CharField(blank=True, db_column='DESON', max_length=50, null=True)),
                ('secconci', models.CharField(blank=True, db_column='SECCONCI', max_length=50, null=True)),
                ('planilha_folha', models.CharField(blank=True, db_column='PLANILHA_FOLHA', max_length=50, null=True)),
                ('planilha_convenio', models.CharField(blank=True, db_column='PLANILHA_CONVENIO', max_length=50, null=True)),
                ('fecha_ponto', models.CharField(blank=True, db_column='FECHA_PONTO', max_length=50, null=True)),
                ('obs_folha', models.TextField(blank=True, db_column='OBS_FOLHA', null=True)),
                ('sst', models.CharField(blank=True, db_column='SST', max_length=50, null=True)),
                ('dt_adiantamento', models.DateField(blank=True, db_column='DT_ADIANTAMENTO', null=True)),
                ('perc_adiantamento', models.CharField(blank=True, db_column='PERC_ADIANTAMENTO', max_length=20, null=True)),
                ('periodo_ponto', models.CharField(blank=True, db_column='PERIODO_PONTO', max_length=50, null=True)),
                ('tipo_ponto', models.CharField(blank=True, db_column='TIPO_PONTO', max_length=50, null=True)),
                ('info_ferias', models.TextField(blank=True, db_column='INFO_FERIAS', null=True)),
                ('obs_rescisao', models.TextField(blank=True, db_column='OBS_RESCISAO', null=True)),
                ('login_out_sist', models.CharField(blank=True, db_column='LOGIN_OUT_SIST', max_length=100, null=True)),
                ('sen_out_sist', models.CharField(blank=True, db_column='SEN_OUT_SIST', max_length=100, null=True)),
                ('cad_pat', models.CharField(blank=True, db_column='CAD_PAT', max_length=50, null=True)),
                ('usu_pat', models.CharField(blank=True, db_column='USU_PAT', max_length=100, null=True)),
                ('sen_pat', models.CharField(blank=True, db_column='SEN_PAT', max_length=100, null=True)),
                ('dt_envio_cct', models.DateField(blank=True, db_column='DT_ENVIO_CCT', null=True)),
                ('opc_rec_patronal', models.CharField(blank=True, db_column='OPC_REC_PATRONAL', max_length=50, null=True)),
                ('dt_venc_conec_social', models.DateField(blank=True, db_column='DT_VENC_CONEC_SOCIAL', null=True)),
                ('sd_login', models.CharField(blank=True, db_column='SD_LOGIN', max_length=100, null=True)),
                ('sd_senha', models.CharField(blank=True, db_column='SD_SENHA', max_length=100, null=True)),
                ('sd_email', models.EmailField(blank=True, db_column='SD_EMAIL', max_length=254, null=True)),
                ('fgts_digital', models.CharField(blank=True, db_column='FGTS_DIGITAL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'geral_planilha_gerencial',
                'managed': True,
            },
        ),
    ]
