# Generated by Django 5.2.5 on 2025-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sistemas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('DIA', 'Dia Corrido'), ('DIA_UTIL', 'Dia Útil')], max_length=10)),
                ('descricao', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'db_table': 'periodos_entrega',
                'ordering': ['tipo', 'dia'],
                'unique_together': {('dia', 'tipo')},
            },
        ),
    ]

