# Generated by Django 5.2.5 on 2025-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agendaregra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAdmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['descricao'],
                'db_table': 'pg_tipos_admissao',
            },
        ),
    ]
